# Choose your desired base image
FROM jupyter/scipy-notebook:latest

# Create a Python 2.x environment using conda including at least the ipython kernel
# and the kernda utility. Add any additional packages you want available for use
# in a Python 2 notebook to the first line here (e.g., pandas, matplotlib, etc.)
RUN conda create --quiet --yes -p $CONDA_DIR/envs/python2 python=2.7 ipython ipykernel kernda && \
    conda clean -tipsy

#RUN conda create --quiet --yes -n python27 python=2.7 ipython ipykernel kernda && \
#    conda clean -tipsy

RUN conda install --quiet --yes -p $CONDA_DIR/envs/python2 python=2.7 \
    'conda-forge::blas=*=openblas' \
    'pyaml' \
    'ipywidgets=7.2*' \
    'pandas=0.23*' \
    'numexpr=2.6*' \
    'matplotlib=2.2*' \
    'scipy=1.1*' \
    'seaborn=0.8*' \
    'scikit-learn=0.19*' \
    'scikit-image=0.14*' \
    'sympy=1.1*' 

USER root

# Create a global kernelspec in the image and modify it so that it properly activates
# the python2 conda environment.
RUN $CONDA_DIR/envs/python2/bin/python -m ipykernel install && \
$CONDA_DIR/envs/python2/bin/pip install pyaml rospkg rosbag-pandas && \
$CONDA_DIR/envs/python2/bin/kernda -o -y /usr/local/share/jupyter/kernels/python2/kernel.json

# Switch back to jovyan to avoid accidental container runs as root
USER $NB_UID

# And in your notebook, start with..
# import sys
# sys.path.append("/usr/lib/python2.7/dist-packages")
# sys.path.append("/opt/ros/kinetic/lib/python2.7/dist-packages")
